#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --function-name
      echo --function-region
      echo --function-module-path
      echo --function-payload-path
      echo --function-payload-body
      echo --function-environment-path
      echo --reload-config
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-name")
      if [ -n "$2" ]; then
        func_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-region")
      if [ -n "$2" ]; then
        func_region="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-handler-path")
      if [ -n "$2" ]; then
        func_handler_path="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-payload-path")
      if [ -n "$2" ]; then
        func_payload_path="$2"
        func_payload_body="$(cat $func_payload_path)"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-payload-body")
      if [ -n "$2" ]; then
        func_payload_body="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-environment-path")
      if [ -n "$2" ]; then
        func_env_path="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--reload-config")
      reload_config=1
      shift 1
      ;;
  esac
done


if [ -z "$func_name" ]; then
  echo "[require] --function-name" 1>&2
  exit 1
fi


profile=${profile:-"default"}
reload_config=${reload_config:-0}

invoker="$SAW_DIR_LIB/lambda/invoke.js"
cache_prefix="$SAW_DIR_CACHE/lambda/${alias_key}"
cache_path="${cache_prefix}/${func_name}"

conf=""
if [ -r "$cache_path" -a $reload_config -eq 0 ]; then
  conf="$(cat $cache_path)"
else
  conf=$(aws --profile $profile lambda get-function-configuration --function-name $func_name)
  [ $? -ne 0 ] && exit 1
  mkdir -p $cache_prefix
  echo "$conf" > $cache_path
fi

func_region=${func_region:-"ap-northeast-1"}
func_payload_body=${func_payload_body:-""}
func_handler_path=${func_handler_path:-"$(pwd)/index.js"}
func_handler_string=$(echo "$conf" | jq -r .Handler)
func_role=$(echo "$conf" | jq -r .Role)
func_timeout=$(echo "$conf" | jq -r .Timeout)
func_mem=$(echo "$conf" | jq -r .MemorySize)
func_ver=$(echo "$conf" | jq -r .Version)
func_arn=$(echo "$conf" | jq -r .FunctionArn)

export AWS_REGION="$func_region"
export AWS_LAMBDA_HANDLER_PATH="$func_handler_path"
export AWS_LAMBDA_HANDLER_STRING="$func_handler_string"
export AWS_LAMBDA_PAYLOAD_BODY="$func_payload_body"
export AWS_LAMBDA_FUNCTION_NAME="$func_name"
export AWS_LAMBDA_TIMEOUT="$func_timeout"
export AWS_LAMBDA_MEMORY_LIMIT="$func_mem"
export AWS_LAMBDA_FUNCTION_VERSION="$func_ver"
export AWS_LAMBDA_FUNCTION_ARN="$func_arn"


creds=$(aws --profile $profile sts assume-role --role-arn $func_role --role-session-name saw-exec-local)
[ $? -ne 0 ] && exit 1

export AWS_ACCESS_KEY_ID=$(echo "$creds" | jq -r .Credentials.AccessKeyId)
export AWS_SECRET_ACCESS_KEY=$(echo "$creds" | jq -r .Credentials.SecretAccessKey)
export AWS_SESSION_TOKEN=$(echo "$creds" | jq -r .Credentials.SessionToken)


if [ -n "$func_env_path" -a -r "$func_env_path"]; then
  for key in $(jq -r keys[] $func_env_path); do
    export $key=$(jq -r .$key $func_env_path)
  done
fi


node $invoker
