#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --function-name
      echo --payload-path
      echo --output-path
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-name")
      if [ -n "$2" ]; then
        func_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--payload-path")
      if [ -n "$2" ]; then
        payload_path="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--output-path")
      if [ -n "$2" ]; then
        output_path="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}
output_path=${output_path:-"/dev/null"}


if [ -n "$payload_path" ]; then
  payload="--payload file://$payload_path"
fi

aws lambda invoke --profile $profile --function-name $func_name --log-type Tail $payload $output_path | jq -r .LogResult | base64 -D
