#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --function-name
      echo --zip-path
      echo --publish
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--function-name")
      if [ -n "$2" ]; then
        func_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--zip-path")
      if [ -n "$2" ]; then
        zip_path="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--publish")
      publish_new_version=1
      shift 1
      ;;
  esac
done

profile=${profile:-"default"}

if [ -z "$zip_path" ]; then
  npm run build > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    zip_path="$(pwd)/${func_name}.zip"
  fi
fi

publish_opt="--no-publish"
if [ "$publish_new_version" = "1" ]; then
  publish_opt="--publish"
fi

aws lambda update-function-code --profile $profile --function-name $func_name --zip-file fileb://$zip_path $publish_opt
