#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --table-name
      echo --segments
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--table-name")
      if [ -n "$2" ]; then
        table_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--segments")
      if [ -n "$2" ]; then
        segments="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}
total_segments=${segments:-"5"}


cmd="paste -d $'\n'"
for i in $(seq 0 $(($total_segments - 1))); do
  sub="aws --profile $profile dynamodb scan --query 'Count' --table-name $table_name --total-segments $total_segments --segment $i"
  cmd="$cmd <($sub)"
done
eval $cmd | awk '{sum+=$1} END{print sum}'
