#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --no-cache
      echo --output
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--no-cache")
      nocache=1
      shift 1
      ;;
    "--output")
      if [ -n "$2" ]; then
        output="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}
nocache=${nocache:-0}
output=${output:-""}

if [ -n "$SAW_DIR_CACHE" ]; then
  cache_prefix="$SAW_DIR_CACHE/ec2/${profile}"
  cache_path="${cache_prefix}/instancelist"
fi

do_desc_instances=0
if [ $nocache -eq 1 ]; then
  do_desc_instances=1
elif [ ! -r "$cache_path" ]; then
  do_desc_instances=1
elif [ -z "$(find $cache_path -mmin -60)" ]; then
  do_desc_instances=1
fi

if [ $do_desc_instances -eq 1 ]; then
  query='Reservations[].Instances[].{"instanceid":InstanceId,"name":Tags[?Key==`Name`].Value|[0],"state":State.Name,"privateip":PrivateIpAddress,"az":Placement.AvailabilityZone,"instancetype":InstanceType,"launchtime":LaunchTime,"tags":Tags}|sort_by(@,&"launchtime")|reverse(@)'
  list=$(aws ec2 describe-instances --profile "$profile" --query "$query" --output json | jq '.[]|.tags = (.tags//[]|from_entries)')
  if [ -n "$cache_path" ]; then
    mkdir -p $cache_prefix
    echo "$list" > $cache_path
  fi
else
  list=$(cat $cache_path)
fi

if [ "$output" = "json" ]; then
  echo "$list"
else
  echo "$list" | jq -r '.launchtime = (.launchtime[:19])|.tags = (.tags//[]|to_entries|[.[].value]|join("/"))|to_entries|[.[].value|.//"--"]|join(",")' | column -t -s ',' | peco
fi
