#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --bucket
      echo --key
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--bucket")
      if [ -n "$2" ]; then
        bucket="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--key")
      if [ -n "$2" ]; then
        key="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}


version_id=$(saw s3 list-object-versions --profile $profile --bucket $bucket --prefix $key  | awk '{print $5}')
aws s3api get-object --profile $profile --bucket $bucket --key $key --version-id $version_id ./$(basename $key)
