#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --bucket
      echo --key
      echo --alias-key
      echo --role-name
      echo --external-id
      exit
      ;;
    "--bucket")
      if [ -n "$2" ]; then
        bucket="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--key")
      if [ -n "$2" ]; then
        key="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--alias-key")
      if [ -n "$2" ]; then
        alias_key="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--role-name")
      if [ -n "$2" ]; then
        role_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--external-id")
      if [ -n "$2" ]; then
        external_id="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


map=$(cat $SAW_DIR_CONF/accounts.json)

alias_key=${alias_key:-"$(echo $map | jq -r .default.alias_key)"}
role_name=${role_name:-"$(echo $map | jq -r .default.role_name)"}
external_id=${external_id:-"$(echo $map | jq -r .default.external_id)"}


if [ -z "$SAW_DEFAULT_PROFILE" ]; then
  profile="${alias_key}-${role_name}"
  saw iam assume-role --alias-key $alias_key --role-name $role_name --external-id $external_id > /dev/null
else
  profile="$SAW_DEFAULT_PROFILE"
fi


version_id=$(saw s3 list-object-versions --bucket $bucket --prefix $key --alias-key $alias_key --role-name $role_name --external-id $external_id | awk '{print $5}')


aws s3api get-object --profile $profile --bucket $bucket --key $key --version-id $version_id ./$(basename $key)
