#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --bucket
      echo --prefix
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--bucket")
      if [ -n "$2" ]; then
        bucket="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--prefix")
      if [ -n "$2" ]; then
        prefix="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}


query='Versions[].{"key":Key,"version-id":VersionId,"last-modified":LastModified,"size":Size,"is-latest":IsLatest}|sort_by(@,&"key")'
list=$(aws s3api list-object-versions --profile $profile --bucket $bucket --prefix $prefix --query $query --output text)

if [ $? -eq 0 ]; then
  echo "$list" | fzf
else
  echo "$list"
fi
