#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --bucket
      echo --prefix
      echo --alias-key
      echo --role-name
      echo --external-id
      exit
      ;;
    "--bucket")
      if [ -n "$2" ]; then
        bucket="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--prefix")
      if [ -n "$2" ]; then
        prefix="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--alias-key")
      if [ -n "$2" ]; then
        alias_key="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--role-name")
      if [ -n "$2" ]; then
        role_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--external-id")
      if [ -n "$2" ]; then
        external_id="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


map=$(cat $SAW_DIR_CONF/accounts.json)

alias_key=${alias_key:-"$(echo $map | jq -r .default.alias_key)"}
role_name=${role_name:-"$(echo $map | jq -r .default.role_name)"}
external_id=${external_id:-"$(echo $map | jq -r .default.external_id)"}


if [ -z "$SAW_DEFAULT_PROFILE" ]; then
  profile="${alias_key}-${role_name}"
  saw iam assume-role --alias-key $alias_key --role-name $role_name --external-id $external_id > /dev/null
else
  profile="$SAW_DEFAULT_PROFILE"
fi


query='Versions[].{"key":Key,"version-id":VersionId,"last-modified":LastModified,"size":Size,"is-latest":IsLatest}|sort_by(@,&"key")'
list=$(aws s3api list-object-versions --profile $profile --bucket $bucket --prefix $prefix --query $query --output text)

if [ $? -eq 0 ]; then
  echo "$list" | peco
else
  echo "$list"
fi
