#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done

profile=${profile:-"default"}

list=$(aws kinesis list-streams --profile $profile --output text | awk '{print $2}')

if [ $? -eq 0 ]; then
  echo "$list" | fzf
else
  echo "$list"
  exit 1
fi
