#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --stream-name
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--stream-name")
      if [ -n "$2" ]; then
        stream_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done


profile=${profile:-"default"}

if [ -z "$stream_name" ]; then
  stream_name=$(saw kinesis list-streams --profile $profile)
fi


shards=$(aws kinesis describe-stream --profile $profile --stream-name $stream_name --query 'StreamDescription.Shards' | jq -r 'map({id:.ShardId,key_range:{start:.HashKeyRange.StartingHashKey,end:.HashKeyRange.EndingHashKey},seq_range:{start:.SequenceNumberRange.StartingSequenceNumber,end:.SequenceNumberRange.EndingSequenceNumber},parent:.ParentShardId,adjacent:.AdjacentParentShardId})')


list=$(echo "$shards" | jq -r '.[]|"\(.id) \(.key_range.start) \(.key_range.end) \(.seq_range.start) \(.seq_range.end) \(.parent) \(.adjacent)"')
[ -z "$list" ] && exit 1


while read id k_start k_end s_start s_end parent adjacent; do
  id=$((10#${id#shardId-}))
  [ "$parent" != 'null' ] && parent=$((10#${parent#shardId-}))
  [ "$adjacent" != 'null' ] && adjacent=$((10#${adjacent#shardId-}))

  ancestor='-'
  reshard='-'
  if   [ "$parent" != 'null' -a "$adjacent" != 'null' ]; then
    ancestor="$parent+$adjacent"
    reshard=">"
  elif [ "$parent" != 'null' ]; then
    ancestor="$parent"
    reshard="<"
  fi

  [ "$s_end" == 'null' ] && status='OPEN' || status='CLOSED'

  row="$ancestor $reshard $id $status $k_start $k_end $s_start $s_end"
  echo $row | awk '{printf("%7s %s %3s %-6s %40s %40s %s %s\n",$1,$2,$3,$4,$5,$6,$7,$8)}'
done < <(echo "$list") | fzf
