#!/bin/bash

set -o pipefail
set -e

for opt in "$@"; do
  case "$opt" in
    "--list-options")
      echo --list-options
      echo --profile
      echo --stream-name
      exit
      ;;
    "--profile")
      if [ -n "$2" ]; then
        profile="$2"
        shift 2
      else
        shift 1
      fi
      ;;
    "--stream-name")
      if [ -n "$2" ]; then
        stream_name="$2"
        shift 2
      else
        shift 1
      fi
      ;;
  esac
done

profile=${profile:-"default"}

if [ -z "$stream_name" ]; then
  stream_name=$(saw kinesis list-streams --profile $profile)
fi


shards=$(saw kinesis list-shards --profile $profile --stream-name $stream_name)

num=$(echo "$shards" | wc -l)
if [ $(($num)) -ge 2 ]; then
  echo 'Has been selected 2 or more lines' 1>&2
  exit 1
fi

read parents reshard_type shard_id status k_start k_end s_start s_end <<< $(echo $shards)

if [ "$status" != 'OPEN' ]; then
  echo 'Has been selected a closed shard' 1>&2
  exit 1
fi


id="shardId-$(printf %012s $shard_id)"
new_key=$(echo "($k_start + $k_end) / 2" | bc)

aws kinesis split-shard --profile $profile --stream-name $stream_name --shard-to-split $id --new-starting-hash-key $new_key
